### ISSUE TITLE
HashNet的作用

### ISSUE THREAD

**Issue by harlen1212** [MaxChanger/ImageRetrieval#11]
请问模型中HashNet文件夹作用是什么，没有找到HashNet的使用

**Comment by MaxChanger** [comment]
您好，该项目时间有点久远了。HashNet是一个专门用于Image Retrieval的方案，通过哈希编码来检索图像，可以作为此demo的后续改进方式，现在的DaiNet只是一个CNN模型，取其某个维度的feature用于检索，没有很特殊地对ImageRetrieval设计和处理。
