### ISSUE TITLE
How did you train your model?

### ISSUE THREAD

**Issue by Cabbagehust2507** [MaxChanger/ImageRetrieval#6]

**Comment by MaxChanger** [comment]
For Example2,  `image_retrieval_DaiNet.py`,  you cloud see https://github.com/MaxChanger/pytorch-cifar for more details, or `cd DaiNet` and then `python main_DainNet.py` to begin the training.

For Example1 is not under my control, you can refer to the link given for this part, and I only have his model file.

**Comment by Cabbagehust2507** [comment]
> For Example2, `image_retrieval_DaiNet.py`, you cloud see https://github.com/MaxChanger/pytorch-cifar for more details, or `cd DaiNet` and then `python main_DaiNet.py` to begin the training.
> 
> For Example1 is not under my control, you can refer to the link given for this part, and I only have his model file.

Thank you so much for helping me! I will try that. :)
